
"AIRCRAFT"
"AIRPORT/AIRCRAFT"
"AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA"
"AIRPORT BUILDING NON-TERMINAL - SECURE AREA"
"AIRPORT EXTERIOR - NON-SECURE AREA"
"AIRPORT EXTERIOR - SECURE AREA"
"AIRPORT PARKING LOT"
"AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA"
"AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA"
"AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA"
"AIRPORT TERMINAL UPPER LEVEL - SECURE AREA"
"AIRPORT VENDING ESTABLISHMENT"

"ALLEY"
"ABANDONED BUILDING"
"BRIDGE"
"CEMETARY"

"CONSTRUCTION SITE"

"CHURCH/SYNAGOGUE/PLACE OF WORSHIP"

"APARTMENT"
"CHA APARTMENT"
"CHA HALLWAY/STAIRWELL/ELEVATOR"
"CHA PARKING LOT/GROUNDS"

"APPLIANCE STORE"
"ANIMAL HOSPITAL"
"ATHLETIC CLUB"
"BARBERSHOP"
"BOWLING ALLEY"
"CAR WASH"
"CLEANING STORE"
"COMMERCIAL / BUSINESS OFFICE"
"CONVENIENCE STORE"


"COLLEGE/UNIVERSITY GROUNDS"
"COLLEGE/UNIVERSITY RESIDENCE HALL"

"DAY CARE CENTER"

"BAR OR TAVERN"

"COIN OPERATED MACHINE"
"ATM (AUTOMATIC TELLER MACHINE)"
"BANK"
"CREDIT UNION"
"CURRENCY EXCHANGE"

"CTA BUS"
"CTA BUS STOP"
"CTA GARAGE/OTHER PROPERTY"

"CTA PLATFORM"
"CTA TRAIN"

"AUTO"
"DELIVERY TRUCK"

