
"AIRCRAFT"
"AIRPORT/AIRCRAFT"
"AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA"
"AIRPORT BUILDING NON-TERMINAL - SECURE AREA"
"AIRPORT EXTERIOR - NON-SECURE AREA"
"AIRPORT EXTERIOR - SECURE AREA"
"AIRPORT PARKING LOT"
"AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA"
"AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA"
"AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA"
"AIRPORT TERMINAL UPPER LEVEL - SECURE AREA"
"AIRPORT VENDING ESTABLISHMENT"

"ALLEY"
"ABANDONED BUILDING"
"BRIDGE"
"CEMETARY"
"VACANT LOT/LAND"

"CONSTRUCTION SITE"

"CHURCH/SYNAGOGUE/PLACE OF WORSHIP"

"APARTMENT"
"CHA APARTMENT"
"CHA HALLWAY/STAIRWELL/ELEVATOR"
"CHA PARKING LOT/GROUNDS"

"PARKING LOT/GARAGE(NON.RESID.)"
"POLICE FACILITY/VEH PARKING LOT"
"RESIDENCE-GARAGE"

"RESIDENCE PORCH/HALLWAY"
"RESIDENTIAL YARD (FRONT/BACK)"

"RESTAURANT"

"APPLIANCE STORE"
"ANIMAL HOSPITAL"
"ATHLETIC CLUB"
"BARBERSHOP"
"BOWLING ALLEY"
"CAR WASH"
"CLEANING STORE"
"COMMERCIAL / BUSINESS OFFICE"
"CONVENIENCE STORE"
"DEPARTMENT STORE"
"DRUG STORE"
"GAS STATION"
"GROCERY FOOD STORE"
"PAWN SHOP"
"SMALL RETAIL STORE"

"FACTORY/MANUFACTURING BUILDING"

"FEDERAL BUILDING"
"GOVERNMENT BUILDING/PROPERTY"

"SPORTS ARENA/STADIUM"


"COLLEGE/UNIVERSITY GROUNDS"
"COLLEGE/UNIVERSITY RESIDENCE HALL"
"SCHOOL, PRIVATE, BUILDING"
"SCHOOL, PRIVATE, GROUNDS"
"SCHOOL, PUBLIC, BUILDING"
"SCHOOL, PUBLIC, GROUNDS"

"SIDEWALK"
"STREET"

"DAY CARE CENTER"

"BAR OR TAVERN"
"TAVERN/LIQUOR STORE"

"COIN OPERATED MACHINE"
"ATM (AUTOMATIC TELLER MACHINE)"
"BANK"
"CREDIT UNION"
"CURRENCY EXCHANGE"
"SAVINGS AND LOAN"

"FIRE STATION"

"CTA BUS"
"CTA BUS STOP"
"CTA GARAGE/OTHER PROPERTY"

"TAXICAB"

"CTA PLATFORM"
"CTA TRAIN"
"OTHER RAILROAD PROP / TRAIN DEPOT"

"HIGHWAY/EXPRESSWAY"

"HOSPITAL BUILDING/GROUNDS"
"MEDICAL/DENTAL OFFICE"

"PORCH"
"POOL ROOM"
"OTHER COMMERCIAL TRANSPORTATION"
"AUTO"
"DELIVERY TRUCK"
"DRIVEWAY - RESIDENTIAL"
"FOREST PRESERVE"
"LAKEFRONT/WATERFRONT/RIVERBANK"
"MOVIE HOUSE/THEATER"
"NURSING HOME/RETIREMENT HOME"
"NURSING HOME"
"OTHER"

"PARK PROPERTY"

"HOTEL/MOTEL"

"HOUSE"
"RESIDENCE"

"JAIL / LOCK-UP FACILITY"

"LIBRARY"



